### ISSUE TITLE
Authentication failed!

### ISSUE THREAD

**Issue by evert0n** [aspose-total/Aspose.Total-for-Cloud#19]
Got hit by the `Authentication failed!` issue

Similar to what's reported in this thread https://forum.aspose.com/t/authentication-failed-for-all-api-calls/163824

But we're using the NodeJS SDK 
https://github.com/aspose-total/Aspose.Total-for-Cloud/blob/master/SDKs/Aspose.Storage-Cloud-SDK-for-NodeJS/

Found a off couple issues

* On NPM (https://www.npmjs.com/package/asposestoragecloud) it's points the source code for this repo, but looking into the code it's seems outdate in here, and a different version got published as 1.0.3 to NPM
* Then comparing `1.0.2` which was working for us but once upgraded to latest `1.0.3` stopped and we started getting the error message `Authentication failed!` found that the code that generated the signature used in request was changed slight were in version `1.0.2` it used to use a `digest('base64')` but on version `1.0.3` passed to be `digest('hex')` as can be checked on the screenshot: [Imgur](https://i.imgur.com/Bgqedmz.png) changing `1.0.3` from `hex` to `base64` works for us.

**Comment by naeem244** [comment]
Hi Everton Yoshitani,

Thanks for sharing details. 

We have published latest version on npm with base64.

**Comment by duffyg** [comment]
Hi Naeem24,
I see that asposestoragecloud has been fixed, but what about asposepdfcloud and asposewordscloud? They're still using digest('hex') in their version of lib/api-client.js. When will they be fixed?

**Comment by naeem244** [comment]
Hi Everton Yoshitani,

We have updated all Node.js SDKs.

**Comment by evert0n** [comment]
@naeem244 Thanks
